### ISSUE TITLE
Interested in upstreaming this to RustCrypto?

### ISSUE THREAD

**Issue by tarcieri** [blackbeam/rust-rabbit#1]
Hello,

The https://github.com/RustCrypto organization maintains several cryptographic implementations with a common trait-based interface to the various implementations.

We received a request for `rabbit` and noticed your implementation:

https://github.com/RustCrypto/stream-ciphers/issues/171

Would you be interested in upstreaming it? We provide ongoing maintenance for several algorithm implementations if that's something that interests you.

**Comment by blackbeam** [comment]
Hi. I don't mind to upstream this into RustCrypto/stream-ciphers. You want me to file a PR?

**Comment by tarcieri** [comment]
Sounds great! Thank you very much!

**Comment by blackbeam** [comment]
It is now in RustCrypto (see RustCrypto/stream-ciphers#171, RustCrypto/stream-ciphers#182)
